POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "Angel",
    "dateOfBirth": "2001-11-22",
    "ssn": "461235-048V",
    "gender": "male",
    "occupation": "Life-Long Learner"
}