POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "Angel",
    "dateOfBirth": "2001-11-22",
    "ssn": "461235-048V",
    "gender": "male",
    "occupation": "Life-Long Learner"
}

###

GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667